[package]
name = "gfx_text"
version = "0.20.0"
authors = ["Kagami Hiiragi <kagami@genshiken.org>"]
description = "Draw text for gfx using freetype."
keywords = ["gfx", "graphics", "text", "freetype", "font"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/PistonDevelopers/gfx_text"
repository = "https://github.com/PistonDevelopers/gfx_text.git"
documentation = "http://docs.piston.rs/gfx_text/gfx_text/"

[dependencies]
gfx = { git = "https://github.com/itadinanta/gfx.git", branch = "rust-oids-0_4_0", version="0.16.1"}
freetype-rs = "0.16"

[features]
default = ["include-font"]
include-font = []

### For examples

[dev-dependencies]
gfx_window_glutin = "0.17.0"
glutin = "0.9.2"
#log = "*"
#env_logger = "*"
